/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/messages': typeof MessagesRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/messages': typeof MessagesRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/messages': typeof MessagesRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacts' | '/messages' | '/api/public/whatsapp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacts' | '/messages' | '/api/public/whatsapp-webhook'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/messages'
    | '/api/public/whatsapp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  MessagesRoute: typeof MessagesRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  MessagesRoute: MessagesRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
