-- NOTE: These tables already exist in the live database (public schema).
-- This file documents the schema for reference only.
-- Do NOT run this migration against the live database.

-- CREATE TABLE public.clientes (
--   id uuid NOT NULL DEFAULT gen_random_uuid(),
--   nombre text NOT NULL,
--   apellidos text NOT NULL,
--   direccion text, numero text, piso text, puerta text,
--   codigo_postal character, municipio text, provincia text,
--   telefono_fijo text, telefono_movil text, email text, anotaciones text,
--   created_at timestamptz NOT NULL DEFAULT now(),
--   updated_at timestamptz NOT NULL DEFAULT now(),
--   CONSTRAINT clientes_pkey PRIMARY KEY (id)
-- );

-- CREATE TABLE public.mensajes_whatsapp (
--   id uuid NOT NULL DEFAULT gen_random_uuid(),
--   cliente_id uuid NOT NULL REFERENCES public.clientes(id),
--   nombre_cliente text NOT NULL,
--   comunidad_id uuid REFERENCES public.comunidades(id),
--   telefono_destino text NOT NULL,
--   mensaje text NOT NULL,
--   estado estado_mensaje NOT NULL DEFAULT 'pendiente',
--   whatsapp_message_id text,
--   enviado_at timestamptz, entregado_at timestamptz, leido_at timestamptz,
--   error_detalle text,
--   created_at timestamptz NOT NULL DEFAULT now(),
--   updated_at timestamptz NOT NULL DEFAULT now(),
--   CONSTRAINT mensajes_whatsapp_pkey PRIMARY KEY (id)
-- );

-- CREATE TABLE public.mensajes_entrantes (
--   id uuid NOT NULL DEFAULT gen_random_uuid(),
--   whatsapp_message_id text, from_phone text NOT NULL,
--   message_body text, received_at timestamptz NOT NULL DEFAULT now(),
--   CONSTRAINT mensajes_entrantes_pkey PRIMARY KEY (id)
-- );
